### ISSUE TITLE
No OG image on Twitter 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#1110]
See this thread: https://twitter.com/TomZarebczan/status/1169359128894070784

Missing images for FAQ artcles and /get link.

/Android shows the below - I was still expecting the main og image if not on Android. 
![image](https://user-images.githubusercontent.com/8120721/64292378-4557a200-cf38-11e9-90ce-c290ea8921c3.png)

**Comment by jsigwart** [comment]
It looks like we're missing some tags?

https://cards-dev.twitter.com/validator
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup

<img width="1022" alt="Screen Shot 2019-09-05 at 9 53 05 PM" src="https://user-images.githubusercontent.com/1363664/64435044-9ff71800-d076-11e9-983d-6f5b5fef06a2.png">

**Comment by NetOperatorWibby** [comment]
Those tags have nothing to do with the image.

**Comment by NetOperatorWibby** [comment]
I think this may be some sort of issue (caching?) with Twitter. Here's what I see when I text myself:

<img width="248" alt="SS 2019-09-06 at 11 25 48 AM" src="https://user-images.githubusercontent.com/1288356/64444141-160c7680-d099-11e9-9699-62158287e833.png">

Our site also has `og:image` fields populated so idk what I could do from here.

**Comment by jsigwart** [comment]
Whoops, last comment I used beta.lbry.tv instead of lbry.com. I'm getting the same thing Tom is when I check the validators:

<img width="1027" alt="Screen Shot 2019-09-06 at 10 13 17 AM" src="https://user-images.githubusercontent.com/1363664/64446992-24559500-d08f-11e9-93d1-168bb82a15bc.png">

Facebook looks like it is grabbing the screenshot image, but we're missing the og:url tag:

<img width="1006" alt="Screen Shot 2019-09-06 at 10 16 01 AM" src="https://user-images.githubusercontent.com/1363664/64447208-ae056280-d08f-11e9-89e0-5168f3a1c21b.png">

**Comment by jsigwart** [comment]
Is this the same as growth#355?

**Comment by kauffj** [comment]
I added a cache bust in https://github.com/lbryio/lbry.com/commit/67b4b8121525f5213834f61a6a4777a13fcc5e41

I filed https://github.com/lbryio/growth/issues/410 for creating a FAQ social image

And https://github.com/lbryio/growth/issues/359 exists for other social image changes

So I'm closing this

**Comment by kauffj** [comment]
@tzarebczan if there's something that should still be open here, please let me know
