### ISSUE TITLE
Consider moving website to a more traditional CMS

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry.com#508]
While Github is great, a more traditional CMS like WordPress, SquareSpace, Weebly, Magento, etc. can give us more flexibility when creating landing pages, better control of forms, and ready-to-go integrations and formatting to make blogs and other content types look professional and sleek.

**Comment by Invariant-Change** [comment]
I totally agree. While SquareSpace, Weebly, Magento aren't the best solutions, WordPress is due to its large and amazing community. And it's a solid platform that most people are familiar with.

**WordPress** with **Divi** is the perfect solution. Very lightweight with built-in marketing tools and SEO options. It allows anyone to build unique and amazing looking landing pages in just a few minutes.

Divi also just included an amazing **React** Divi **API**. Check it out.

https://youtu.be/vtkGEb6BnA8

WordPress is 1/3 of the worlds internet and Divi is WordPress's number page builder... because it's the perfect solution for creating working solutions quickly and easily saving so much time and money.

The comparison I always make is, why use machine code when we have dos and why use dos when we have Windows? It's the evolution of things!

**Comment by Invariant-Change** [comment]
*I'm currently working on building a Divi React Module to utilise LBRY.

I see Divi and LBRY as a good pair that can work together in many situations.

**Comment by ITwrx** [comment]
i would like to recommend using a framework like laravel instead of choosing a cms like wordpress. The two options will attract different types of contributors so you might base your decision on what LBRY needs to attract for the website. Although, the draw for designers (as opposed to devs) can still be influenced by what you choose for css, frontend frameworks, etc. if you went the laravel route.
