### ISSUE TITLE
Allow token resend after email verification failure

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.com#981]
#### Issue Summary
If a user gets multiple verification emails from the same device and tries to click an old one, it will just say "invalid email or verification form".  We can make this error more descriptive (will do now on Master), but can we also give them an option to resend the email again?

**Comment by kauffj** [comment]
@tzarebczan does the endpoint exist for this? Can you update ticket with more specifics if it does or add tickets to internal APIs if it does not?

**Comment by tzarebczan** [comment]
Yep, the api is: https://api.lbry.com/user_emai/resend_token, passing both their auth token and email address. Maybe @tiger5226 / @nikooo777 could confirm if we can repass the same email confirmation auth token, or if it has to be the main one.

**Comment by nikooo777** [comment]
I am not 100% sure, the problem with confirming an email is that the token you pass is relative to an user so that if you're trying to claim an email for another user, both will be merged.

So I believe that without auth token there isn't much that can be done. Now what you mean by main auth token I'm not 100% sure. Trying wouldn't hurt though?

**Comment by tiger5226** [comment]
An email scoped token does not have authorization to send a verification email. This is what gets sent with the verification email. We could add the email scope for the resend token api. This way if they hit that problem, they can click a button to resend an email with a new token. I would suggest we return a `498 Token Expired` http response if they try to verify with an expired verification token. This way we can then show the button, otherwise, all other errors are actual errors.

**Comment by tzarebczan** [comment]
Ah, that's why I opened https://github.com/lbryio/internal-apis/issues/593
